/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateledgerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateledgerRequest{}

// CreateledgerRequest struct for CreateledgerRequest
type CreateledgerRequest struct {
	Name     string   `json:"name"`
	MetaData MetaData `json:"meta_data"`
}

type _CreateledgerRequest CreateledgerRequest

// NewCreateledgerRequest instantiates a new CreateledgerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateledgerRequest(name string, metaData MetaData) *CreateledgerRequest {
	this := CreateledgerRequest{}
	this.Name = name
	this.MetaData = metaData
	return &this
}

// NewCreateledgerRequestWithDefaults instantiates a new CreateledgerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateledgerRequestWithDefaults() *CreateledgerRequest {
	this := CreateledgerRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateledgerRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateledgerRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateledgerRequest) SetName(v string) {
	o.Name = v
}

// GetMetaData returns the MetaData field value
func (o *CreateledgerRequest) GetMetaData() MetaData {
	if o == nil {
		var ret MetaData
		return ret
	}

	return o.MetaData
}

// GetMetaDataOk returns a tuple with the MetaData field value
// and a boolean to check if the value has been set.
func (o *CreateledgerRequest) GetMetaDataOk() (*MetaData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaData, true
}

// SetMetaData sets field value
func (o *CreateledgerRequest) SetMetaData(v MetaData) {
	o.MetaData = v
}

func (o CreateledgerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateledgerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["meta_data"] = o.MetaData
	return toSerialize, nil
}

func (o *CreateledgerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"meta_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateledgerRequest := _CreateledgerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateledgerRequest)

	if err != nil {
		return err
	}

	*o = CreateledgerRequest(varCreateledgerRequest)

	return err
}

type NullableCreateledgerRequest struct {
	value *CreateledgerRequest
	isSet bool
}

func (v NullableCreateledgerRequest) Get() *CreateledgerRequest {
	return v.value
}

func (v *NullableCreateledgerRequest) Set(val *CreateledgerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateledgerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateledgerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateledgerRequest(val *CreateledgerRequest) *NullableCreateledgerRequest {
	return &NullableCreateledgerRequest{value: val, isSet: true}
}

func (v NullableCreateledgerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateledgerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
