/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetBalanceMonitor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBalanceMonitor{}

// GetBalanceMonitor struct for GetBalanceMonitor
type GetBalanceMonitor struct {
	MonitorId   string    `json:"monitor_id"`
	BalanceId   string    `json:"balance_id"`
	Condition   Condition `json:"condition"`
	Description string    `json:"description"`
	CallBackUrl string    `json:"call_back_url"`
	CreatedAt   string    `json:"created_at"`
}

type _GetBalanceMonitor GetBalanceMonitor

// NewGetBalanceMonitor instantiates a new GetBalanceMonitor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBalanceMonitor(monitorId string, balanceId string, condition Condition, description string, callBackUrl string, createdAt string) *GetBalanceMonitor {
	this := GetBalanceMonitor{}
	this.MonitorId = monitorId
	this.BalanceId = balanceId
	this.Condition = condition
	this.Description = description
	this.CallBackUrl = callBackUrl
	this.CreatedAt = createdAt
	return &this
}

// NewGetBalanceMonitorWithDefaults instantiates a new GetBalanceMonitor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBalanceMonitorWithDefaults() *GetBalanceMonitor {
	this := GetBalanceMonitor{}
	return &this
}

// GetMonitorId returns the MonitorId field value
func (o *GetBalanceMonitor) GetMonitorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MonitorId
}

// GetMonitorIdOk returns a tuple with the MonitorId field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetMonitorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonitorId, true
}

// SetMonitorId sets field value
func (o *GetBalanceMonitor) SetMonitorId(v string) {
	o.MonitorId = v
}

// GetBalanceId returns the BalanceId field value
func (o *GetBalanceMonitor) GetBalanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BalanceId
}

// GetBalanceIdOk returns a tuple with the BalanceId field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetBalanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceId, true
}

// SetBalanceId sets field value
func (o *GetBalanceMonitor) SetBalanceId(v string) {
	o.BalanceId = v
}

// GetCondition returns the Condition field value
func (o *GetBalanceMonitor) GetCondition() Condition {
	if o == nil {
		var ret Condition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetConditionOk() (*Condition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *GetBalanceMonitor) SetCondition(v Condition) {
	o.Condition = v
}

// GetDescription returns the Description field value
func (o *GetBalanceMonitor) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetBalanceMonitor) SetDescription(v string) {
	o.Description = v
}

// GetCallBackUrl returns the CallBackUrl field value
func (o *GetBalanceMonitor) GetCallBackUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallBackUrl
}

// GetCallBackUrlOk returns a tuple with the CallBackUrl field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetCallBackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallBackUrl, true
}

// SetCallBackUrl sets field value
func (o *GetBalanceMonitor) SetCallBackUrl(v string) {
	o.CallBackUrl = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetBalanceMonitor) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetBalanceMonitor) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetBalanceMonitor) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o GetBalanceMonitor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBalanceMonitor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monitor_id"] = o.MonitorId
	toSerialize["balance_id"] = o.BalanceId
	toSerialize["condition"] = o.Condition
	toSerialize["description"] = o.Description
	toSerialize["call_back_url"] = o.CallBackUrl
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *GetBalanceMonitor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"monitor_id",
		"balance_id",
		"condition",
		"description",
		"call_back_url",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBalanceMonitor := _GetBalanceMonitor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBalanceMonitor)

	if err != nil {
		return err
	}

	*o = GetBalanceMonitor(varGetBalanceMonitor)

	return err
}

type NullableGetBalanceMonitor struct {
	value *GetBalanceMonitor
	isSet bool
}

func (v NullableGetBalanceMonitor) Get() *GetBalanceMonitor {
	return v.value
}

func (v *NullableGetBalanceMonitor) Set(val *GetBalanceMonitor) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBalanceMonitor) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBalanceMonitor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBalanceMonitor(val *GetBalanceMonitor) *NullableGetBalanceMonitor {
	return &NullableGetBalanceMonitor{value: val, isSet: true}
}

func (v NullableGetBalanceMonitor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBalanceMonitor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
