/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateBalanceMonitorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBalanceMonitorRequest{}

// CreateBalanceMonitorRequest struct for CreateBalanceMonitorRequest
type CreateBalanceMonitorRequest struct {
	BalanceId   string    `json:"balance_id"`
	Condition   Condition `json:"condition"`
	CallBackUrl string    `json:"call_back_url"`
}

type _CreateBalanceMonitorRequest CreateBalanceMonitorRequest

// NewCreateBalanceMonitorRequest instantiates a new CreateBalanceMonitorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBalanceMonitorRequest(balanceId string, condition Condition, callBackUrl string) *CreateBalanceMonitorRequest {
	this := CreateBalanceMonitorRequest{}
	this.BalanceId = balanceId
	this.Condition = condition
	this.CallBackUrl = callBackUrl
	return &this
}

// NewCreateBalanceMonitorRequestWithDefaults instantiates a new CreateBalanceMonitorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBalanceMonitorRequestWithDefaults() *CreateBalanceMonitorRequest {
	this := CreateBalanceMonitorRequest{}
	return &this
}

// GetBalanceId returns the BalanceId field value
func (o *CreateBalanceMonitorRequest) GetBalanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BalanceId
}

// GetBalanceIdOk returns a tuple with the BalanceId field value
// and a boolean to check if the value has been set.
func (o *CreateBalanceMonitorRequest) GetBalanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceId, true
}

// SetBalanceId sets field value
func (o *CreateBalanceMonitorRequest) SetBalanceId(v string) {
	o.BalanceId = v
}

// GetCondition returns the Condition field value
func (o *CreateBalanceMonitorRequest) GetCondition() Condition {
	if o == nil {
		var ret Condition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *CreateBalanceMonitorRequest) GetConditionOk() (*Condition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *CreateBalanceMonitorRequest) SetCondition(v Condition) {
	o.Condition = v
}

// GetCallBackUrl returns the CallBackUrl field value
func (o *CreateBalanceMonitorRequest) GetCallBackUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallBackUrl
}

// GetCallBackUrlOk returns a tuple with the CallBackUrl field value
// and a boolean to check if the value has been set.
func (o *CreateBalanceMonitorRequest) GetCallBackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallBackUrl, true
}

// SetCallBackUrl sets field value
func (o *CreateBalanceMonitorRequest) SetCallBackUrl(v string) {
	o.CallBackUrl = v
}

func (o CreateBalanceMonitorRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBalanceMonitorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balance_id"] = o.BalanceId
	toSerialize["condition"] = o.Condition
	toSerialize["call_back_url"] = o.CallBackUrl
	return toSerialize, nil
}

func (o *CreateBalanceMonitorRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balance_id",
		"condition",
		"call_back_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBalanceMonitorRequest := _CreateBalanceMonitorRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBalanceMonitorRequest)

	if err != nil {
		return err
	}

	*o = CreateBalanceMonitorRequest(varCreateBalanceMonitorRequest)

	return err
}

type NullableCreateBalanceMonitorRequest struct {
	value *CreateBalanceMonitorRequest
	isSet bool
}

func (v NullableCreateBalanceMonitorRequest) Get() *CreateBalanceMonitorRequest {
	return v.value
}

func (v *NullableCreateBalanceMonitorRequest) Set(val *CreateBalanceMonitorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBalanceMonitorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBalanceMonitorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBalanceMonitorRequest(val *CreateBalanceMonitorRequest) *NullableCreateBalanceMonitorRequest {
	return &NullableCreateBalanceMonitorRequest{value: val, isSet: true}
}

func (v NullableCreateBalanceMonitorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBalanceMonitorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
