/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateBalance201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBalance201Response{}

// CreateBalance201Response struct for CreateBalance201Response
type CreateBalance201Response struct {
	BalanceId          string         `json:"balance_id"`
	Balance            int32          `json:"balance"`
	CreditBalance      int32          `json:"credit_balance"`
	DebitBalance       int32          `json:"debit_balance"`
	Currency           string         `json:"currency"`
	CurrencyMultiplier int32          `json:"currency_multiplier"`
	LedgerId           string         `json:"ledger_id"`
	IdentityId         string         `json:"identity_id"`
	CreatedAt          string         `json:"created_at"`
	MetaData           NullableString `json:"meta_data"`
}

type _CreateBalance201Response CreateBalance201Response

// NewCreateBalance201Response instantiates a new CreateBalance201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBalance201Response(balanceId string, balance int32, creditBalance int32, debitBalance int32, currency string, currencyMultiplier int32, ledgerId string, identityId string, createdAt string, metaData NullableString) *CreateBalance201Response {
	this := CreateBalance201Response{}
	this.BalanceId = balanceId
	this.Balance = balance
	this.CreditBalance = creditBalance
	this.DebitBalance = debitBalance
	this.Currency = currency
	this.CurrencyMultiplier = currencyMultiplier
	this.LedgerId = ledgerId
	this.IdentityId = identityId
	this.CreatedAt = createdAt
	this.MetaData = metaData
	return &this
}

// NewCreateBalance201ResponseWithDefaults instantiates a new CreateBalance201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBalance201ResponseWithDefaults() *CreateBalance201Response {
	this := CreateBalance201Response{}
	return &this
}

// GetBalanceId returns the BalanceId field value
func (o *CreateBalance201Response) GetBalanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BalanceId
}

// GetBalanceIdOk returns a tuple with the BalanceId field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetBalanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceId, true
}

// SetBalanceId sets field value
func (o *CreateBalance201Response) SetBalanceId(v string) {
	o.BalanceId = v
}

// GetBalance returns the Balance field value
func (o *CreateBalance201Response) GetBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *CreateBalance201Response) SetBalance(v int32) {
	o.Balance = v
}

// GetCreditBalance returns the CreditBalance field value
func (o *CreateBalance201Response) GetCreditBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditBalance
}

// GetCreditBalanceOk returns a tuple with the CreditBalance field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetCreditBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditBalance, true
}

// SetCreditBalance sets field value
func (o *CreateBalance201Response) SetCreditBalance(v int32) {
	o.CreditBalance = v
}

// GetDebitBalance returns the DebitBalance field value
func (o *CreateBalance201Response) GetDebitBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DebitBalance
}

// GetDebitBalanceOk returns a tuple with the DebitBalance field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetDebitBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DebitBalance, true
}

// SetDebitBalance sets field value
func (o *CreateBalance201Response) SetDebitBalance(v int32) {
	o.DebitBalance = v
}

// GetCurrency returns the Currency field value
func (o *CreateBalance201Response) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CreateBalance201Response) SetCurrency(v string) {
	o.Currency = v
}

// GetCurrencyMultiplier returns the CurrencyMultiplier field value
func (o *CreateBalance201Response) GetCurrencyMultiplier() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrencyMultiplier
}

// GetCurrencyMultiplierOk returns a tuple with the CurrencyMultiplier field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetCurrencyMultiplierOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyMultiplier, true
}

// SetCurrencyMultiplier sets field value
func (o *CreateBalance201Response) SetCurrencyMultiplier(v int32) {
	o.CurrencyMultiplier = v
}

// GetLedgerId returns the LedgerId field value
func (o *CreateBalance201Response) GetLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LedgerId
}

// GetLedgerIdOk returns a tuple with the LedgerId field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LedgerId, true
}

// SetLedgerId sets field value
func (o *CreateBalance201Response) SetLedgerId(v string) {
	o.LedgerId = v
}

// GetIdentityId returns the IdentityId field value
func (o *CreateBalance201Response) GetIdentityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetIdentityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityId, true
}

// SetIdentityId sets field value
func (o *CreateBalance201Response) SetIdentityId(v string) {
	o.IdentityId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateBalance201Response) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateBalance201Response) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateBalance201Response) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetMetaData returns the MetaData field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateBalance201Response) GetMetaData() string {
	if o == nil || o.MetaData.Get() == nil {
		var ret string
		return ret
	}

	return *o.MetaData.Get()
}

// GetMetaDataOk returns a tuple with the MetaData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBalance201Response) GetMetaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetaData.Get(), o.MetaData.IsSet()
}

// SetMetaData sets field value
func (o *CreateBalance201Response) SetMetaData(v string) {
	o.MetaData.Set(&v)
}

func (o CreateBalance201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBalance201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balance_id"] = o.BalanceId
	toSerialize["balance"] = o.Balance
	toSerialize["credit_balance"] = o.CreditBalance
	toSerialize["debit_balance"] = o.DebitBalance
	toSerialize["currency"] = o.Currency
	toSerialize["currency_multiplier"] = o.CurrencyMultiplier
	toSerialize["ledger_id"] = o.LedgerId
	toSerialize["identity_id"] = o.IdentityId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["meta_data"] = o.MetaData.Get()
	return toSerialize, nil
}

func (o *CreateBalance201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balance_id",
		"balance",
		"credit_balance",
		"debit_balance",
		"currency",
		"currency_multiplier",
		"ledger_id",
		"identity_id",
		"created_at",
		"meta_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBalance201Response := _CreateBalance201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBalance201Response)

	if err != nil {
		return err
	}

	*o = CreateBalance201Response(varCreateBalance201Response)

	return err
}

type NullableCreateBalance201Response struct {
	value *CreateBalance201Response
	isSet bool
}

func (v NullableCreateBalance201Response) Get() *CreateBalance201Response {
	return v.value
}

func (v *NullableCreateBalance201Response) Set(val *CreateBalance201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBalance201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBalance201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBalance201Response(val *CreateBalance201Response) *NullableCreateBalance201Response {
	return &NullableCreateBalance201Response{value: val, isSet: true}
}

func (v NullableCreateBalance201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBalance201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
