/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBalance{}

// GetBalance struct for GetBalance
type GetBalance struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type _GetBalance GetBalance

// NewGetBalance instantiates a new GetBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBalance(id string, name string, createdAt string) *GetBalance {
	this := GetBalance{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewGetBalanceWithDefaults instantiates a new GetBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBalanceWithDefaults() *GetBalance {
	this := GetBalance{}
	return &this
}

// GetId returns the Id field value
func (o *GetBalance) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetBalance) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetBalance) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetBalance) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetBalance) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetBalance) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetBalance) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetBalance) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetBalance) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o GetBalance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *GetBalance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBalance := _GetBalance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBalance)

	if err != nil {
		return err
	}

	*o = GetBalance(varGetBalance)

	return err
}

type NullableGetBalance struct {
	value *GetBalance
	isSet bool
}

func (v NullableGetBalance) Get() *GetBalance {
	return v.value
}

func (v *NullableGetBalance) Set(val *GetBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBalance(val *GetBalance) *NullableGetBalance {
	return &NullableGetBalance{value: val, isSet: true}
}

func (v NullableGetBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
