/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateIdentityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateIdentityRequest{}

// UpdateIdentityRequest struct for UpdateIdentityRequest
type UpdateIdentityRequest struct {
	IdentityType string    `json:"identity_type"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	OtherNames   string    `json:"other_names"`
	Gender       string    `json:"gender"`
	Dob          string    `json:"dob"`
	EmailAddress string    `json:"email_address"`
	PhoneNumber  string    `json:"phone_number"`
	Nationality  string    `json:"nationality"`
	Street       string    `json:"street"`
	Country      string    `json:"country"`
	State        string    `json:"state"`
	PostCode     string    `json:"post_code"`
	City         string    `json:"city"`
	CreatedAt    string    `json:"created_at"`
	MetaData     MetaData2 `json:"meta_data"`
}

type _UpdateIdentityRequest UpdateIdentityRequest

// NewUpdateIdentityRequest instantiates a new UpdateIdentityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateIdentityRequest(identityType string, firstName string, lastName string, otherNames string, gender string, dob string, emailAddress string, phoneNumber string, nationality string, street string, country string, state string, postCode string, city string, createdAt string, metaData MetaData2) *UpdateIdentityRequest {
	this := UpdateIdentityRequest{}
	this.IdentityType = identityType
	this.FirstName = firstName
	this.LastName = lastName
	this.OtherNames = otherNames
	this.Gender = gender
	this.Dob = dob
	this.EmailAddress = emailAddress
	this.PhoneNumber = phoneNumber
	this.Nationality = nationality
	this.Street = street
	this.Country = country
	this.State = state
	this.PostCode = postCode
	this.City = city
	this.CreatedAt = createdAt
	this.MetaData = metaData
	return &this
}

// NewUpdateIdentityRequestWithDefaults instantiates a new UpdateIdentityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateIdentityRequestWithDefaults() *UpdateIdentityRequest {
	this := UpdateIdentityRequest{}
	return &this
}

// GetIdentityType returns the IdentityType field value
func (o *UpdateIdentityRequest) GetIdentityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityType
}

// GetIdentityTypeOk returns a tuple with the IdentityType field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetIdentityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityType, true
}

// SetIdentityType sets field value
func (o *UpdateIdentityRequest) SetIdentityType(v string) {
	o.IdentityType = v
}

// GetFirstName returns the FirstName field value
func (o *UpdateIdentityRequest) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *UpdateIdentityRequest) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value
func (o *UpdateIdentityRequest) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *UpdateIdentityRequest) SetLastName(v string) {
	o.LastName = v
}

// GetOtherNames returns the OtherNames field value
func (o *UpdateIdentityRequest) GetOtherNames() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtherNames
}

// GetOtherNamesOk returns a tuple with the OtherNames field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetOtherNamesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtherNames, true
}

// SetOtherNames sets field value
func (o *UpdateIdentityRequest) SetOtherNames(v string) {
	o.OtherNames = v
}

// GetGender returns the Gender field value
func (o *UpdateIdentityRequest) GetGender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *UpdateIdentityRequest) SetGender(v string) {
	o.Gender = v
}

// GetDob returns the Dob field value
func (o *UpdateIdentityRequest) GetDob() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dob
}

// GetDobOk returns a tuple with the Dob field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetDobOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dob, true
}

// SetDob sets field value
func (o *UpdateIdentityRequest) SetDob(v string) {
	o.Dob = v
}

// GetEmailAddress returns the EmailAddress field value
func (o *UpdateIdentityRequest) GetEmailAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailAddress, true
}

// SetEmailAddress sets field value
func (o *UpdateIdentityRequest) SetEmailAddress(v string) {
	o.EmailAddress = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *UpdateIdentityRequest) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *UpdateIdentityRequest) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetNationality returns the Nationality field value
func (o *UpdateIdentityRequest) GetNationality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nationality
}

// GetNationalityOk returns a tuple with the Nationality field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetNationalityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nationality, true
}

// SetNationality sets field value
func (o *UpdateIdentityRequest) SetNationality(v string) {
	o.Nationality = v
}

// GetStreet returns the Street field value
func (o *UpdateIdentityRequest) GetStreet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Street
}

// GetStreetOk returns a tuple with the Street field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetStreetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Street, true
}

// SetStreet sets field value
func (o *UpdateIdentityRequest) SetStreet(v string) {
	o.Street = v
}

// GetCountry returns the Country field value
func (o *UpdateIdentityRequest) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *UpdateIdentityRequest) SetCountry(v string) {
	o.Country = v
}

// GetState returns the State field value
func (o *UpdateIdentityRequest) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *UpdateIdentityRequest) SetState(v string) {
	o.State = v
}

// GetPostCode returns the PostCode field value
func (o *UpdateIdentityRequest) GetPostCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostCode
}

// GetPostCodeOk returns a tuple with the PostCode field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetPostCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostCode, true
}

// SetPostCode sets field value
func (o *UpdateIdentityRequest) SetPostCode(v string) {
	o.PostCode = v
}

// GetCity returns the City field value
func (o *UpdateIdentityRequest) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *UpdateIdentityRequest) SetCity(v string) {
	o.City = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UpdateIdentityRequest) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UpdateIdentityRequest) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetMetaData returns the MetaData field value
func (o *UpdateIdentityRequest) GetMetaData() MetaData2 {
	if o == nil {
		var ret MetaData2
		return ret
	}

	return o.MetaData
}

// GetMetaDataOk returns a tuple with the MetaData field value
// and a boolean to check if the value has been set.
func (o *UpdateIdentityRequest) GetMetaDataOk() (*MetaData2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaData, true
}

// SetMetaData sets field value
func (o *UpdateIdentityRequest) SetMetaData(v MetaData2) {
	o.MetaData = v
}

func (o UpdateIdentityRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateIdentityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identity_type"] = o.IdentityType
	toSerialize["first_name"] = o.FirstName
	toSerialize["last_name"] = o.LastName
	toSerialize["other_names"] = o.OtherNames
	toSerialize["gender"] = o.Gender
	toSerialize["dob"] = o.Dob
	toSerialize["email_address"] = o.EmailAddress
	toSerialize["phone_number"] = o.PhoneNumber
	toSerialize["nationality"] = o.Nationality
	toSerialize["street"] = o.Street
	toSerialize["country"] = o.Country
	toSerialize["state"] = o.State
	toSerialize["post_code"] = o.PostCode
	toSerialize["city"] = o.City
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["meta_data"] = o.MetaData
	return toSerialize, nil
}

func (o *UpdateIdentityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identity_type",
		"first_name",
		"last_name",
		"other_names",
		"gender",
		"dob",
		"email_address",
		"phone_number",
		"nationality",
		"street",
		"country",
		"state",
		"post_code",
		"city",
		"created_at",
		"meta_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateIdentityRequest := _UpdateIdentityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateIdentityRequest)

	if err != nil {
		return err
	}

	*o = UpdateIdentityRequest(varUpdateIdentityRequest)

	return err
}

type NullableUpdateIdentityRequest struct {
	value *UpdateIdentityRequest
	isSet bool
}

func (v NullableUpdateIdentityRequest) Get() *UpdateIdentityRequest {
	return v.value
}

func (v *NullableUpdateIdentityRequest) Set(val *UpdateIdentityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateIdentityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateIdentityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateIdentityRequest(val *UpdateIdentityRequest) *NullableUpdateIdentityRequest {
	return &NullableUpdateIdentityRequest{value: val, isSet: true}
}

func (v NullableUpdateIdentityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateIdentityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
