/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateAccount201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccount201Response{}

// CreateAccount201Response struct for CreateAccount201Response
type CreateAccount201Response struct {
	AccountId  string         `json:"account_id"`
	Name       string         `json:"name"`
	Number     string         `json:"number"`
	BankName   string         `json:"bank_name"`
	Currency   string         `json:"currency"`
	CreatedAt  string         `json:"created_at"`
	BalanceId  string         `json:"balance_id"`
	IdentityId string         `json:"identity_id"`
	LedgerId   string         `json:"ledger_id"`
	MetaData   NullableString `json:"meta_data"`
	Ledger     NullableString `json:"ledger"`
	Balance    NullableString `json:"balance"`
	Identity   NullableString `json:"identity"`
}

type _CreateAccount201Response CreateAccount201Response

// NewCreateAccount201Response instantiates a new CreateAccount201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccount201Response(accountId string, name string, number string, bankName string, currency string, createdAt string, balanceId string, identityId string, ledgerId string, metaData NullableString, ledger NullableString, balance NullableString, identity NullableString) *CreateAccount201Response {
	this := CreateAccount201Response{}
	this.AccountId = accountId
	this.Name = name
	this.Number = number
	this.BankName = bankName
	this.Currency = currency
	this.CreatedAt = createdAt
	this.BalanceId = balanceId
	this.IdentityId = identityId
	this.LedgerId = ledgerId
	this.MetaData = metaData
	this.Ledger = ledger
	this.Balance = balance
	this.Identity = identity
	return &this
}

// NewCreateAccount201ResponseWithDefaults instantiates a new CreateAccount201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccount201ResponseWithDefaults() *CreateAccount201Response {
	this := CreateAccount201Response{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *CreateAccount201Response) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *CreateAccount201Response) SetAccountId(v string) {
	o.AccountId = v
}

// GetName returns the Name field value
func (o *CreateAccount201Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAccount201Response) SetName(v string) {
	o.Name = v
}

// GetNumber returns the Number field value
func (o *CreateAccount201Response) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *CreateAccount201Response) SetNumber(v string) {
	o.Number = v
}

// GetBankName returns the BankName field value
func (o *CreateAccount201Response) GetBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankName, true
}

// SetBankName sets field value
func (o *CreateAccount201Response) SetBankName(v string) {
	o.BankName = v
}

// GetCurrency returns the Currency field value
func (o *CreateAccount201Response) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CreateAccount201Response) SetCurrency(v string) {
	o.Currency = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateAccount201Response) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateAccount201Response) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetBalanceId returns the BalanceId field value
func (o *CreateAccount201Response) GetBalanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BalanceId
}

// GetBalanceIdOk returns a tuple with the BalanceId field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetBalanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceId, true
}

// SetBalanceId sets field value
func (o *CreateAccount201Response) SetBalanceId(v string) {
	o.BalanceId = v
}

// GetIdentityId returns the IdentityId field value
func (o *CreateAccount201Response) GetIdentityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetIdentityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityId, true
}

// SetIdentityId sets field value
func (o *CreateAccount201Response) SetIdentityId(v string) {
	o.IdentityId = v
}

// GetLedgerId returns the LedgerId field value
func (o *CreateAccount201Response) GetLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LedgerId
}

// GetLedgerIdOk returns a tuple with the LedgerId field value
// and a boolean to check if the value has been set.
func (o *CreateAccount201Response) GetLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LedgerId, true
}

// SetLedgerId sets field value
func (o *CreateAccount201Response) SetLedgerId(v string) {
	o.LedgerId = v
}

// GetMetaData returns the MetaData field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateAccount201Response) GetMetaData() string {
	if o == nil || o.MetaData.Get() == nil {
		var ret string
		return ret
	}

	return *o.MetaData.Get()
}

// GetMetaDataOk returns a tuple with the MetaData field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccount201Response) GetMetaDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MetaData.Get(), o.MetaData.IsSet()
}

// SetMetaData sets field value
func (o *CreateAccount201Response) SetMetaData(v string) {
	o.MetaData.Set(&v)
}

// GetLedger returns the Ledger field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateAccount201Response) GetLedger() string {
	if o == nil || o.Ledger.Get() == nil {
		var ret string
		return ret
	}

	return *o.Ledger.Get()
}

// GetLedgerOk returns a tuple with the Ledger field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccount201Response) GetLedgerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ledger.Get(), o.Ledger.IsSet()
}

// SetLedger sets field value
func (o *CreateAccount201Response) SetLedger(v string) {
	o.Ledger.Set(&v)
}

// GetBalance returns the Balance field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateAccount201Response) GetBalance() string {
	if o == nil || o.Balance.Get() == nil {
		var ret string
		return ret
	}

	return *o.Balance.Get()
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccount201Response) GetBalanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Balance.Get(), o.Balance.IsSet()
}

// SetBalance sets field value
func (o *CreateAccount201Response) SetBalance(v string) {
	o.Balance.Set(&v)
}

// GetIdentity returns the Identity field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CreateAccount201Response) GetIdentity() string {
	if o == nil || o.Identity.Get() == nil {
		var ret string
		return ret
	}

	return *o.Identity.Get()
}

// GetIdentityOk returns a tuple with the Identity field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccount201Response) GetIdentityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Identity.Get(), o.Identity.IsSet()
}

// SetIdentity sets field value
func (o *CreateAccount201Response) SetIdentity(v string) {
	o.Identity.Set(&v)
}

func (o CreateAccount201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccount201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["name"] = o.Name
	toSerialize["number"] = o.Number
	toSerialize["bank_name"] = o.BankName
	toSerialize["currency"] = o.Currency
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["balance_id"] = o.BalanceId
	toSerialize["identity_id"] = o.IdentityId
	toSerialize["ledger_id"] = o.LedgerId
	toSerialize["meta_data"] = o.MetaData.Get()
	toSerialize["ledger"] = o.Ledger.Get()
	toSerialize["balance"] = o.Balance.Get()
	toSerialize["identity"] = o.Identity.Get()
	return toSerialize, nil
}

func (o *CreateAccount201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"name",
		"number",
		"bank_name",
		"currency",
		"created_at",
		"balance_id",
		"identity_id",
		"ledger_id",
		"meta_data",
		"ledger",
		"balance",
		"identity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccount201Response := _CreateAccount201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccount201Response)

	if err != nil {
		return err
	}

	*o = CreateAccount201Response(varCreateAccount201Response)

	return err
}

type NullableCreateAccount201Response struct {
	value *CreateAccount201Response
	isSet bool
}

func (v NullableCreateAccount201Response) Get() *CreateAccount201Response {
	return v.value
}

func (v *NullableCreateAccount201Response) Set(val *CreateAccount201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccount201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccount201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccount201Response(val *CreateAccount201Response) *NullableCreateAccount201Response {
	return &NullableCreateAccount201Response{value: val, isSet: true}
}

func (v NullableCreateAccount201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccount201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
