/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccount200Response{}

// GetAccount200Response struct for GetAccount200Response
type GetAccount200Response struct {
	AccountId  string    `json:"account_id"`
	Name       string    `json:"name"`
	Number     string    `json:"number"`
	BankName   string    `json:"bank_name"`
	Currency   string    `json:"currency"`
	CreatedAt  string    `json:"created_at"`
	BalanceId  string    `json:"balance_id"`
	IdentityId string    `json:"identity_id"`
	LedgerId   string    `json:"ledger_id"`
	MetaData   MetaData2 `json:"meta_data"`
	Ledger     Ledger    `json:"ledger"`
	Balance    Balance   `json:"balance"`
	Identity   Identity  `json:"identity"`
}

type _GetAccount200Response GetAccount200Response

// NewGetAccount200Response instantiates a new GetAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccount200Response(accountId string, name string, number string, bankName string, currency string, createdAt string, balanceId string, identityId string, ledgerId string, metaData MetaData2, ledger Ledger, balance Balance, identity Identity) *GetAccount200Response {
	this := GetAccount200Response{}
	this.AccountId = accountId
	this.Name = name
	this.Number = number
	this.BankName = bankName
	this.Currency = currency
	this.CreatedAt = createdAt
	this.BalanceId = balanceId
	this.IdentityId = identityId
	this.LedgerId = ledgerId
	this.MetaData = metaData
	this.Ledger = ledger
	this.Balance = balance
	this.Identity = identity
	return &this
}

// NewGetAccount200ResponseWithDefaults instantiates a new GetAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccount200ResponseWithDefaults() *GetAccount200Response {
	this := GetAccount200Response{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *GetAccount200Response) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *GetAccount200Response) SetAccountId(v string) {
	o.AccountId = v
}

// GetName returns the Name field value
func (o *GetAccount200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAccount200Response) SetName(v string) {
	o.Name = v
}

// GetNumber returns the Number field value
func (o *GetAccount200Response) GetNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *GetAccount200Response) SetNumber(v string) {
	o.Number = v
}

// GetBankName returns the BankName field value
func (o *GetAccount200Response) GetBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankName, true
}

// SetBankName sets field value
func (o *GetAccount200Response) SetBankName(v string) {
	o.BankName = v
}

// GetCurrency returns the Currency field value
func (o *GetAccount200Response) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GetAccount200Response) SetCurrency(v string) {
	o.Currency = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetAccount200Response) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetAccount200Response) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetBalanceId returns the BalanceId field value
func (o *GetAccount200Response) GetBalanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BalanceId
}

// GetBalanceIdOk returns a tuple with the BalanceId field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetBalanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceId, true
}

// SetBalanceId sets field value
func (o *GetAccount200Response) SetBalanceId(v string) {
	o.BalanceId = v
}

// GetIdentityId returns the IdentityId field value
func (o *GetAccount200Response) GetIdentityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetIdentityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdentityId, true
}

// SetIdentityId sets field value
func (o *GetAccount200Response) SetIdentityId(v string) {
	o.IdentityId = v
}

// GetLedgerId returns the LedgerId field value
func (o *GetAccount200Response) GetLedgerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LedgerId
}

// GetLedgerIdOk returns a tuple with the LedgerId field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetLedgerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LedgerId, true
}

// SetLedgerId sets field value
func (o *GetAccount200Response) SetLedgerId(v string) {
	o.LedgerId = v
}

// GetMetaData returns the MetaData field value
func (o *GetAccount200Response) GetMetaData() MetaData2 {
	if o == nil {
		var ret MetaData2
		return ret
	}

	return o.MetaData
}

// GetMetaDataOk returns a tuple with the MetaData field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetMetaDataOk() (*MetaData2, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetaData, true
}

// SetMetaData sets field value
func (o *GetAccount200Response) SetMetaData(v MetaData2) {
	o.MetaData = v
}

// GetLedger returns the Ledger field value
func (o *GetAccount200Response) GetLedger() Ledger {
	if o == nil {
		var ret Ledger
		return ret
	}

	return o.Ledger
}

// GetLedgerOk returns a tuple with the Ledger field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetLedgerOk() (*Ledger, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ledger, true
}

// SetLedger sets field value
func (o *GetAccount200Response) SetLedger(v Ledger) {
	o.Ledger = v
}

// GetBalance returns the Balance field value
func (o *GetAccount200Response) GetBalance() Balance {
	if o == nil {
		var ret Balance
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetBalanceOk() (*Balance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *GetAccount200Response) SetBalance(v Balance) {
	o.Balance = v
}

// GetIdentity returns the Identity field value
func (o *GetAccount200Response) GetIdentity() Identity {
	if o == nil {
		var ret Identity
		return ret
	}

	return o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value
// and a boolean to check if the value has been set.
func (o *GetAccount200Response) GetIdentityOk() (*Identity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identity, true
}

// SetIdentity sets field value
func (o *GetAccount200Response) SetIdentity(v Identity) {
	o.Identity = v
}

func (o GetAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["name"] = o.Name
	toSerialize["number"] = o.Number
	toSerialize["bank_name"] = o.BankName
	toSerialize["currency"] = o.Currency
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["balance_id"] = o.BalanceId
	toSerialize["identity_id"] = o.IdentityId
	toSerialize["ledger_id"] = o.LedgerId
	toSerialize["meta_data"] = o.MetaData
	toSerialize["ledger"] = o.Ledger
	toSerialize["balance"] = o.Balance
	toSerialize["identity"] = o.Identity
	return toSerialize, nil
}

func (o *GetAccount200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"name",
		"number",
		"bank_name",
		"currency",
		"created_at",
		"balance_id",
		"identity_id",
		"ledger_id",
		"meta_data",
		"ledger",
		"balance",
		"identity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAccount200Response := _GetAccount200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAccount200Response)

	if err != nil {
		return err
	}

	*o = GetAccount200Response(varGetAccount200Response)

	return err
}

type NullableGetAccount200Response struct {
	value *GetAccount200Response
	isSet bool
}

func (v NullableGetAccount200Response) Get() *GetAccount200Response {
	return v.value
}

func (v *NullableGetAccount200Response) Set(val *GetAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccount200Response(val *GetAccount200Response) *NullableGetAccount200Response {
	return &NullableGetAccount200Response{value: val, isSet: true}
}

func (v NullableGetAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
