/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Createledger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Createledger{}

// Createledger struct for Createledger
type Createledger struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type _Createledger Createledger

// NewCreateledger instantiates a new Createledger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateledger(id string, name string, createdAt string) *Createledger {
	this := Createledger{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewCreateledgerWithDefaults instantiates a new Createledger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateledgerWithDefaults() *Createledger {
	this := Createledger{}
	return &this
}

// GetId returns the Id field value
func (o *Createledger) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Createledger) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Createledger) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Createledger) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Createledger) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Createledger) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Createledger) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Createledger) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Createledger) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o Createledger) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Createledger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Createledger) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateledger := _Createledger{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateledger)

	if err != nil {
		return err
	}

	*o = Createledger(varCreateledger)

	return err
}

type NullableCreateledger struct {
	value *Createledger
	isSet bool
}

func (v NullableCreateledger) Get() *Createledger {
	return v.value
}

func (v *NullableCreateledger) Set(val *Createledger) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateledger) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateledger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateledger(val *Createledger) *NullableCreateledger {
	return &NullableCreateledger{value: val, isSet: true}
}

func (v NullableCreateledger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateledger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
