/*
Blnk

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetLedger200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLedger200Response{}

// GetLedger200Response struct for GetLedger200Response
type GetLedger200Response struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type _GetLedger200Response GetLedger200Response

// NewGetLedger200Response instantiates a new GetLedger200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLedger200Response(id string, name string, createdAt string) *GetLedger200Response {
	this := GetLedger200Response{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewGetLedger200ResponseWithDefaults instantiates a new GetLedger200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLedger200ResponseWithDefaults() *GetLedger200Response {
	this := GetLedger200Response{}
	return &this
}

// GetId returns the Id field value
func (o *GetLedger200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetLedger200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetLedger200Response) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetLedger200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetLedger200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetLedger200Response) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetLedger200Response) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetLedger200Response) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetLedger200Response) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o GetLedger200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLedger200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *GetLedger200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLedger200Response := _GetLedger200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetLedger200Response)

	if err != nil {
		return err
	}

	*o = GetLedger200Response(varGetLedger200Response)

	return err
}

type NullableGetLedger200Response struct {
	value *GetLedger200Response
	isSet bool
}

func (v NullableGetLedger200Response) Get() *GetLedger200Response {
	return v.value
}

func (v *NullableGetLedger200Response) Set(val *GetLedger200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLedger200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLedger200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLedger200Response(val *GetLedger200Response) *NullableGetLedger200Response {
	return &NullableGetLedger200Response{value: val, isSet: true}
}

func (v NullableGetLedger200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLedger200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
